### ISSUE TITLE
fix: hass 2021.12.07 Network stack restart

### ISSUE THREAD

**Issue by DeTurbo** [laszlojakab/homeassistant-easycontrols#46] opened 2022-01-01 08:41 UTC
Dear all,

After I got Hass on the current stabile release (2021.12.07), I got a disconnect on the KNX bus every half minute.

It passed quite a while of troubleshooting until I got via the following post the hint that this behavior is triggered by a repeatedly occurring restart of the network stack.

The cause of this behavior is helios_EasyControls. 

After disabling the integration the system is stable.

I just tried the recently released beta of helios_EasyControls. Unfortunately the same behavior.

So far I have not managed to find the point where helios_EasyControls crashed the network stack

**Comment by DeTurbo** [comment] 2022-01-01 08:41
https://github.com/home-assistant/core/issues/59170

**Comment by laszlojakab** [comment] 2022-01-01 10:59
Hi @DeTurbo,

Could you please try the integration from https://github.com/laszlojakab/homeassistant-easycontrols/tree/fix/network-stack-restart branch? I have removed the thread locking from the code. Maybe locking cause your problem. The integration won't work correctly with this modification (sensors may become unavailable time to time) but I could check with this modification if it is the source of the problem.

**Comment by DeTurbo** [comment] 2022-01-02 08:34
I overwrote the threadsafe_controller.py with your changed code, re-enabled the integration and performed a restart.
Unfortunately with the same result :-(

I mean but now the abort comes much more regular, namely exactly every 30 seconds I see in the log connection aborts.
After disabling the integration it runs like butter.

**Comment by laszlojakab** [comment] 2022-01-02 09:46
Hi @DeTurbo,
I think the problem is not in the integration itself. Looking through the code I haven't find anything which could cause the disconnection from KNX bus. Maybe the problem is in the underlaying package EazyCtrl. This package handles the communication with the Helios unit. Probably we should contact to the author of this package.  I'm not familier with KNX, but as I see XKNX code it uses UDP for communication. Could it be that UDP packages are lost (and that causes the KNX disconnection) because of high CPU usage? Did you notice high CPU usage?

**Comment by DeTurbo** [comment] 2022-01-02 09:59
The CPU utilization is extremely low. Slightly higher with helios integration enabled, but averaging around 7%.
I run Hass virtualized on an ESXi with a lot of performance.

The crashes do not only affect KNX. With KNX it is immediately noticeable because the connection from the KNX IP interface disconnects because Homeassistent does not respond for a short time. At the same time, the entities receive the value "not available", whereupon then some event triggers, with which then the automatisms no longer clear.

But I use another Helios integration as a plugin. Also there I see the value "not available" for all sensors for the period of the abort.

It works as if something restarts every 30 seconds,

**Comment by laszlojakab** [comment] 2022-01-02 13:33
Which plugin do you use?

**Comment by DeTurbo** [comment] 2022-01-03 06:44
https://github.com/asev/homeassistant-helios

**Comment by laszlojakab** [comment] 2022-01-07 21:44
@DeTurbo could you please test agan with https://github.com/laszlojakab/homeassistant-easycontrols/tree/fix/network-stack-restart branch?

**Comment by elupus** [comment] 2022-01-08 22:24
You can't be using threading.lock on anything that is called from home assistant event loop (that is any async function, @callback marked functions or properties of entities) i recommend you don't use any async code in the custom component at all if the lib is not async. Then the threaded executors is used in home assistant.

**Comment by elupus** [comment] 2022-01-08 22:26
The branch looks better since the lib does looks async at first glance.

**Comment by elupus** [comment] 2022-01-08 22:29
Here is likely one of the bugs: https://github.com/laszlojakab/homeassistant-easycontrols/blob/a1280ebfe600d4d156d5b6ad7576d172ab6d7ff3/custom_components/easycontrols/eazyctrl_mod.py#L477

time.sleep is a bug no no in async code. Use await asyncio.sleep()

**Comment by laszlojakab** [comment] 2022-01-09 10:06
@elupus thanks for the feedback. Probably EazyCtrl external package should be rewritten in async (eazyctrl_mod.py is just a hacky test if it is solves the the problem). By the way I have changed time.sleep to asyncio.sleep in async functions. Still waiting for a feedback from @DeTurbo if it solves the original problem.

**Comment by DeTurbo** [comment] 2022-01-09 10:38
Looks good now.

Since yesterday evening no more disconnects to KNX IP Interface.

**Comment by laszlojakab** [comment] 2022-01-09 13:10
Ok, I will contact to the EazyCtrl package owner to release an async version of the package, next I will release a new version of the integration.

**Comment by laszlojakab** [comment] 2022-01-09 13:39
PR created in EazyCtrl package: https://github.com/baradi09/eazyctrl/pull/6

**Comment by DeTurbo** [comment] 2022-02-12 09:34
@laszlojakab laszlojakab 

Just tried the new beta and the crashes are starting again. - Am back to the custom branch.

**Comment by laszlojakab** [comment] 2022-02-15 19:57
Hi @DeTurbo, the beta does not include the fix for this problem, still waiting for the author of the underlaying eazyctrl package to approve my fix in his package: https://github.com/baradi09/eazyctrl/pull/6
After he approved the modification I need some more time to release a new version because I think there will be some unnecessary code in the integration itself.

**Comment by laszlojakab** [comment] 2022-02-22 22:12
Hello @DeTurbo, could you please test this branch: https://github.com/laszlojakab/homeassistant-easycontrols/tree/fix/use-asyncio-eazyctrl ? This version contains the new eazyctrl package which built on the top of asyncio.

**Comment by laszlojakab** [comment] 2022-02-27 21:10
Hi @DeTurbo! Any feedback about the new version?

**Comment by laszlojakab** [comment] 2022-03-07 20:31
I'm using the modified integration for 2 weeks without an problem. I will release the modified version. Feel free to reopen the issue if you still have this problem.

**Closed by laszlojakab** 2022-03-07 20:31 UTC
Labels: bug
