### ISSUE TITLE
Not connecting

### ISSUE THREAD

**Issue by yvansandoz** [laszlojakab/homeassistant-easycontrols#60] opened 2022-03-03 17:44 UTC
I am running HA OS on a RPi, on the same network as my Helios System, but the integration does not connect to my ventilation using the IP address (192.168.1.127) and a generic name (Helios). Do I miss something?

**Comment by laszlojakab** [comment] 2022-03-03 21:39
Hello @yvansandoz, 
Is Modbus enabled on the device? Under configuration/device tab:

![image](https://user-images.githubusercontent.com/6196882/156656900-da23a68b-27e0-4e52-bc40-1a89706c9077.png)

**Comment by yvansandoz** [comment] 2022-03-04 08:54
Thanks, 

This is the Modbus screen I have with easyControls 3.0 and yes Modbus is activated.



And this is the error message I get in HA:











On 3 Mar 2022, at 22:39, Laszlo Jakab ***@***.***> wrote:


Hello @yvansandoz <https://github.com/yvansandoz>,
Is Modbus enabled on the device? Under configuration/device tab:

 <https://user-images.githubusercontent.com/6196882/156656900-da23a68b-27e0-4e52-bc40-1a89706c9077.png>

**Comment by laszlojakab** [comment] 2022-03-04 21:23
Hi, 
Maybe the problem is the version of your easycontrol. Integration tested on older (<3.0) easycontrols version. The integration based on the eazyctrl python package. Please try to query your device from commandline with the eazyctrl package: 

https://github.com/baradi09/eazyctrl

If it is not working with that than this HA integration also won't work. In that case you could contact to the author of that package. If he could make a working version of the eazyctrl package for your device I could add it to this integration.

**Comment by laszlojakab** [comment] 2022-04-17 19:39
As I see the issue is related to eazyctrl package (https://github.com/baradi09/eazyctrl/issues/7), so I'm closing this issue.

**Closed by laszlojakab** 2022-04-17 19:39 UTC
